DROP TABLE "TRANSACTION" IF EXISTS;
DROP TABLE "USERS" IF EXISTS;
CREATE TABLE TRANSACTION(
  TRANSACTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RECEIVER_ACC VARCHAR(16) NOT NULL,
  SENDER_ACC VARCHAR(16) NOT NULL UNIQUE,
  AMOUNT BIGINT(16) NOT NULL,
  MEDIUM VARCHAR(16) NOT NULL,
);
CREATE TABLE USERS(
  ID bigint(20) NOT NULL PRIMARY KEY,
  EMAIL varchar(255) DEFAULT NULL,
  FIRST_NAME varchar(255) DEFAULT NULL,
);
